replicaCount: 2

controller:
  serviceAccount:
    create: true
    name: efs-csi-controller-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::256461400092:role/finstack-efs-csi-driver-role
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

node:
  enabled: true  # Node DaemonSet runs on managed node group EC2 instances

storageClasses: []  # We manage StorageClass manually
