apiVersion: v1
kind: Service
metadata:
  namespace: finstack
    namespace: finstack
  name: finstack-payment-service
spec:
  type: ClusterIP
  selector:
    app: finstack-payment
  ports:
    - port: 4002
      targetPort: 4002
