apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: finstack
    namespace: finstack
  name: finstack-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finstack-mongodb
  template:
    metadata:
  namespace: finstack
    namespace: finstack
      labels:
        app: finstack-mongodb
    spec:
      containers:
        - name: finstack-mongodb
          image: mongo:7
          ports:
          - containerPort: 27017
