apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: finstack
    namespace: finstack
  name: finstack-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finstack-user
  template:
    metadata:
  namespace: finstack
    namespace: finstack
      labels:
        app: finstack-user
    spec:
      containers:
      - name: finstack-user
        image: gitopssoftinator/finstack-user-service:1.1
        env:
        - name: MONGO_URI
          value: mongodb://finstack-mongodb-service:27017/finstack
        ports:
        - containerPort: 4001
