apiVersion: apps/v1
kind: Deployment
metadata:
  name: finstack-frontend
  namespace: finstack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finstack-frontend
  template:
    metadata:
      labels:
        app: finstack-frontend
    spec:
      containers:
      - name: finstack-frontend
        image: gitopssoftinator/finstack-frontend:latest
        ports:
        - containerPort: 80
