apiVersion: apps/v1
kind: Deployment
metadata:
  name: finstack-payment
  namespace: finstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finstack-payment
  template:
    metadata:
      labels:
        app: finstack-payment
    spec:
      containers:
      - name: finstack-payment
        image: gitopssoftinator/finstack-payment-service:latest
        ports:
        - containerPort: 4002
