apiVersion: v1
kind: Service
metadata:
  name: finstack-gateway-service
  namespace: finstack
spec:
  selector:
    app: finstack-gateway
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
