apiVersion: v1
kind: Service
metadata:
  name: finstack-user-service
  namespace: finstack
spec:
  selector:
    app: finstack-user
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
  type: ClusterIP
