apiVersion: v1
kind: Service
metadata:
  name: finstack-auth-service
  namespace: finstack
spec:
  selector:
    app: finstack-auth
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
