apiVersion: v1
kind: Service
metadata:
  name: finstack-frontend-service
  namespace: finstack
spec:
  selector:
    app: finstack-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
